server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://stats-db:5433/stats
    username: stats_user
    password: stats_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      encoding: UTF-8